# generated by builder.sce: Please do not edit this file
# ------------------------------------------------------
SCIDIR = $$SCILAB_DIR$$
OBJS = $$OBJ$$
SCILIBS = $(SCIDIR)/libs/scicos.a $(SCIDIR)/libs/poly.a $(SCIDIR)/libs/calelm.a $(SCIDIR)/libs/blas.a $(SCIDIR)/libs/lapack.a
LIBRARY =  lib$$MODEL$$
OTHERLIBS = 
include $(SCIDIR)/Makefile.incl
CFLAGS = $(CC_OPTIONS) -I$(SCIDIR)/routines/
FFLAGS = $(FC_OPTIONS) -I$(SCIDIR)/routines/
include $(SCIDIR)/config/Makeso.incl
