#include <stdio.h>

#define XNAME(x,y)  x##y
#define NAME(x,y)   XNAME(x,y)

#define XSTR(x)    #x
#define STR(x)     XSTR(x)

static double TIME=0.0;
char input[50], output[50];
FILE *fprr,*fprw;

#define MODELNAME  STR(MODELN)
#include MODELNAME

char s[1],sf[1],se[1],ss[1],**p;
static char *optarg = NULL ;
static int optind = 1, offset = 0 ;
static int errflg = 0;

double get_scicos_time()
{
  return(TIME);
}


/*Main program */
int main(int argc, char *argv[])
{
  double tf=30;
  double dt=get_tsamp();

  static void usage();
  char * progname = argv[0];
  int c;
  strcpy(input,"");
  strcpy(output,"");
  while ((c = getopt(argc , argv, "i:o:d:t:hv")) != -1)
    switch (c) {
    case 'i':
      strcpy(input,argv[optind-1]);
      break;
    case 'o':
      strcpy(output,argv[optind-1]);
      break;
    case 'd':
      strcpy(s,argv[optind-1]);
      dt=strtod(s,p);
      break;
    case 't':
      strcpy(sf,argv[optind-1]);
      tf=strtod(sf,p);
      break;
    case 'h':
      usage(progname);
      printf("Options : \n");
      printf("         -h for the help  \n");
      printf("         -v for printing the Scilab Version \n");
      printf("         -i for input file name, by default is Terminal \n");
      printf("         -o for output file name, by default is Terminal \n");
      printf("         -d for the clock period, by default is the time of the clock in the scicos scheme \n");
      printf("         -t for the final time, by default is 30 \n");
      return 0;
      break;
    case 'v':
      printf(" Generated by Code_Generation toolbox of Scicos with scilab-4.0 version \n");
      return 0;
      break;
    case '?':
      errflg++;
      break;
    }
    if (errflg){
      usage(progname);
      return 0;
    }
 
  test_sim(tf,dt);
  return 0;
}

static void
usage(prog) char *prog;{
  fprintf(stderr, "Usage: %s [-h] [-v] [-i arg] [-o arg] [-d arg] [-t arg] [-s arg]\n", prog);
}

/*----------------------------------------  External simulation function */ 
int 
test_sim(tf,dt)
 
     double tf,dt; 
{
  double t;
  int nevprt=1;

  if (strlen(input) > 0) aaa=1;
  if (strlen(output)> 0) bbb=1;
  t=0.0;

  NAME(MODEL,_init_blk)();

  while (t<=tf) {
    TIME=t;   
    set_nevprt(nevprt);
    NAME(MODEL,_rt_exec)(NAME(block_,MODEL),z, &t);
    t=t+dt;
  }
  NAME(MODEL,_end)(NAME(block_,MODEL),z, &t);
  return 0;
}
