EXTRA_CFLAGS += -I$(rtai_srctree)/rtai-core/include \
		-I$(rtai_srcdir)/.. \
		-I$(src)/../../../rtai-core/include \
		-I$(src)/../../.. \
		-D__IN_RTAI__

obj-m += rtai_pse51.o

rtai_pse51-objs := $(rtai_objs)
