SHELL = /bin/sh

SCIDIR=../..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = rtailib
NAM = SCI/macros/RTAI

MACROS= rtai_sinus.sci \
	rtai_square.sci \
	rtai_step.sci \
	rtai_scope.sci \
	rtai_led.sci \
	rtai_meter.sci \
	rtai_comedi_datain.sci \
	rtai_comedi_dataout.sci \
	rtai_comedi_dioin.sci \
	rtai_comedi_dioout.sci \
	rtai_pcan_in.sci \
	rtai_pcan_out.sci \
	rtai_cioquad4.sci \
	rtai_mbx_ovrwr_send.sci \
	rtai_mbx_send_if.sci \
	rtai_mbx_rcv_if.sci \
	rtai_mbx_rcv.sci \
	rtai_extdata.sci \
	rtai_fifo.sci \
	RTAICodeGen_.sci

include ../Make.lib
