EXTRA_CFLAGS += -I$(rtai_srctree)/include \
		-I$(rtai_srcdir)/.. \
		-I$(rtai_srcdir)/../../skins \
		-I$(src)/../../include \
		-I$(src)/../.. \
		-I$(rtai_srcdir) \
		-D__IN_RTAI__

obj-m += $(rtai_target).o

$(rtai_target)-objs := $(rtai_objs)
