EXTRA_CFLAGS += -I$(fusion_srctree)/include \
		-I$(fusion_srcdir)/.. \
		-I$(fusion_srcdir)/../../skins \
		-I$(src)/../../include \
		-I$(src)/../.. \
		-I$(fusion_srcdir) \
		$(fusion_extradef)

obj-m += $(rtai_target).o

$(rtai_target)-objs := $(fusion_objs)
