EXTRA_CFLAGS += -I$(fusion_srctree)/include \
		-I$(src)/../../../include \
		-I$(src)/../../.. \
		$(fusion_extradef)

EXTRA_AFLAGS += -I$(fusion_srctree)/include \
		-I$(src)/../../../include \
		-I$(src)/../../.. \
		-Iarch/ia64/kernel \
		$(fusion_extradef)

obj-m += rtai_hal.o

rtai_hal-objs := $(fusion_objs)
