EXTRA_CFLAGS += -I$(rtai_srctree)/rtai-core/include \
		-I$(rtai_srcdir) \
		-I$(src)/../../rtai-core/include \
		-I$(src)/../.. \
		$(rtai_extradef) \
		-D__IN_RTAI__

obj-m += rtai_comedi.o

rtai_comedi-objs := $(rtai_objs)
