--- /usr/lib/scilab-2.7/macros/scicos/Makefile	2004-01-23 09:34:22.000000000 +0100
+++ Makefile	2004-01-23 09:31:44.000000000 +0100
@@ -24,7 +24,7 @@
 	SaveAs_.sci Save_.sci SaveasInterfFunc_.sci SaveasPalette_.sci \
 	SetDiagramInfo_.sci Setup_.sci Shortcuts_.sci SmartMove_.sci \
 	Undo_.sci Window_.sci Zoomin_.sci Zoomout_.sci  CodeGeneration_.sci \
-	menu_stuff.sci 
+	RTAICodeGen_.sci menu_stuff.sci 
 
 COMPAT= %Block_e.sci %graphics_e.sci %model_e.sci %model_e.sci \
 	%b_i_graphics.sci %s_i_graphics.sci %c_i_graphics.sci \
