EXTRA_CFLAGS += -I$(rtai_srctree)/include \
		-I$(src)/../../../include \
		-I$(src)/../../.. \
		$(rtai_extradef)

EXTRA_AFLAGS += -I$(rtai_srctree)/include \
		-I$(src)/../../../include \
		-I$(src)/../../.. \
		$(rtai_extradef)

obj-m += rtai_hal.o

rtai_hal-objs := $(rtai_objs)
