EXTRA_CFLAGS += -I$(fusion_srctree)/include \
		-I$(fusion_srctree)/skins \
		-I$(fusion_srcdir)/.. \
		-I$(src)/../../include \
		-I$(src)/../.. \
		$(fusion_extradef)

obj-m += $(fusion_target).o

$(fusion_target)-objs := $(fusion_objs)
