EXTRA_CFLAGS += -I$(rtai_srctree)/rtai-core/include \
		-I$(src)/../../../rtai-core/include \
		-I$(src)/../../.. \
		$(rtai_extradef) \
		-D__IN_RTAI__

obj-m += preempt_rt.o

preempt_rt-objs := $(rtai_objs)
