EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(rtai_srctree)/addons/fusion/skins \
		-I$(rtai_srcdir)/.. \
		-I$(src)/../../include \
		-I$(src)/../.. \
		$(rtai_extradef)

obj-m += $(rtai_target).o

$(rtai_target)-objs := $(rtai_objs)
