EXTRA_CFLAGS += -I$(rtai_srctree)/base/include \
		-I$(src)/../include \
		-I$(src)/../.. \
		-D__IN_RTAI__

obj-m += rtai_tasklets.o rtai_signal.o

rtai_tasklets-objs := $(rtai_objs)
rtai_signal-objs := $(rtai_objs)
